package com.tqlab.demo.dal.dao;

import com.tqlab.demo.dal.dataobject.Movies;
import com.tqlab.demo.dal.dataobject.MoviesKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MoviesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVIES
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Delete({
        "delete from MOVIES",
        "where MOVIEID = #{movieid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(MoviesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVIES
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Insert({
        "insert into MOVIES (MOVIEID, STARID, ",
        "TITLE)",
        "values (#{movieid,jdbcType=INTEGER}, #{starid,jdbcType=INTEGER}, ",
        "#{title,jdbcType=VARCHAR})"
    })
    int insert(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVIES
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @InsertProvider(type=MoviesSqlProvider.class, method="insertSelective")
    int insertSelective(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVIES
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Select({
        "select",
        "MOVIEID, STARID, TITLE",
        "from MOVIES",
        "where MOVIEID = #{movieid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="MOVIEID", property="movieid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="STARID", property="starid", jdbcType=JdbcType.INTEGER),
        @Result(column="TITLE", property="title", jdbcType=JdbcType.VARCHAR)
    })
    Movies selectByPrimaryKey(MoviesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVIES
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @UpdateProvider(type=MoviesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Movies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVIES
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Update({
        "update MOVIES",
        "set STARID = #{starid,jdbcType=INTEGER},",
          "TITLE = #{title,jdbcType=VARCHAR}",
        "where MOVIEID = #{movieid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Movies record);
}