package com.tqlab.demo.dal.dao;

import com.tqlab.demo.dal.dataobject.Star;
import com.tqlab.demo.dal.dataobject.StarKey;
import com.tqlab.demo.dal.dataobject.UnionStarMovies2;
import com.tqlab.demo.dal.dataobject.UnionStarMovies;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface StarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Delete({
        "delete from STAR",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(StarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Insert({
        "insert into STAR (ID, FIRSTNAME, ",
        "LASTNAME)",
        "values (#{id,jdbcType=INTEGER}, #{firstname,jdbcType=VARCHAR}, ",
        "#{lastname,jdbcType=VARCHAR})"
    })
    int insert(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @InsertProvider(type=StarSqlProvider.class, method="insertSelective")
    int insertSelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Select({
        "select",
        "ID, FIRSTNAME, LASTNAME",
        "from STAR",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FIRSTNAME", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="LASTNAME", property="lastname", jdbcType=JdbcType.VARCHAR)
    })
    Star selectByPrimaryKey(StarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @UpdateProvider(type=StarSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Update({
        "update STAR",
        "set FIRSTNAME = #{firstname,jdbcType=VARCHAR},",
          "LASTNAME = #{lastname,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Delete({
        "delete from star where id=#{id,jdbcType=INTEGER};"    
    })
    int deleteById(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Select({
        "select count(*) from star;"    
    })
    Integer count();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Select({
        "select sum(id) from star;"    
    })
    Integer sum();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Select({
        "select",
        "ID, FIRSTNAME, LASTNAME",
        "from STAR"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FIRSTNAME", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="LASTNAME", property="lastname", jdbcType=JdbcType.VARCHAR)
    })
    List<Star> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Select({
        "select",
        "ID, FIRSTNAME, LASTNAME",
        "from STAR",
        "where id=#{id,jdbcType=INTEGER};"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FIRSTNAME", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="LASTNAME", property="lastname", jdbcType=JdbcType.VARCHAR)
    })
    Star selectById(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     * demo
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Select({
        "select",
        "limit #{start,jdbcType=INTEGER} #{size,jdbcType=INTEGER}",
        "ID, FIRSTNAME, LASTNAME",
        "from STAR"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FIRSTNAME", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="LASTNAME", property="lastname", jdbcType=JdbcType.VARCHAR)
    })
    List<Star> selectWithPagination(@Param("start") Integer start, @Param("size") Integer size);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Select({
        "select a.*, b.* from star a, movies b where a.id = b.starid"    
    })
    @Results({
        @Result(column="id", property="id"),
        @Result(column="title", property="title"),
        @Result(column="lastname", property="lastname"),
        @Result(column="firstname", property="firstname"),
        @Result(column="movieid", property="movieid")
    })
    List<UnionStarMovies> selectComplex1();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    @Select({
        "select a.id as star_id, a.firstname as name, a.lastname,",    
        "b.movieid, b.title from star a, movies b",    
        "where a.id = b.starid"    
    })
    @Results({
        @Result(column="title", property="title"),
        @Result(column="name", property="firstname"),
        @Result(column="star_id", property="id"),
        @Result(column="lastname", property="lastname"),
        @Result(column="movieid", property="movieid")
    })
    List<UnionStarMovies2> selectComplex2();
}