package com.tqlab.demo.dal.dataobject;

public class AdminKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN.ID
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN.ID
     *
     * @return the value of ADMIN.ID
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN.ID
     *
     * @param id the value for ADMIN.ID
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }
}