package com.tqlab.demo.dal.dataobject;

public class Admin extends AdminKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN.NAME
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN.PWD
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    private String pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN.NAME
     *
     * @return the value of ADMIN.NAME
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN.NAME
     *
     * @param name the value for ADMIN.NAME
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN.PWD
     *
     * @return the value of ADMIN.PWD
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN.PWD
     *
     * @param pwd the value for ADMIN.PWD
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }
}