package com.tqlab.demo.dal.dataobject;

public class MoviesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOVIES.MOVIEID
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    private Integer movieid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOVIES.MOVIEID
     *
     * @return the value of MOVIES.MOVIEID
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOVIES.MOVIEID
     *
     * @param movieid the value for MOVIES.MOVIEID
     *
     * @mbggenerated Mon Jul 16 18:38:33 CST 2012
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }
}